[pytest]

testpaths = tests api_tests

pythonpath = .

python_files = test_*.py

python_classes = Test*

python_functions = test_*

addopts =
    -vs
    --browser chromium
    --browser firefox
    --browser webkit
    --reruns 1
    --reruns-delay 2
    --html=reports/report.html
    --self-contained-html
    --alluredir=reports/allure-results